server:
  port: 8083

spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: rate-service
      port: 27017
      host: localhost
      auto-index-creation: true
  application:
    name: RATE-SERVICE
  config:
    import: optional:configserver:http://localhost:8085