server:
  port: 8083

spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: rateservice
      port: 27017
      host: localhost
      auto-index-creation: true