version: "3.9"
services:
  db:
    image: mysql:latest
    container_name: MySQLMicroservices
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user-service
      MYSQL_USER: juan
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - microservices-data:/var/lib/mysql
volumes:
  microservices-data: